src/lib.rs

In current stable ShouldRetry is not usable because it is not public

Make ShouldRetry public

---

src/lib.rs

Introduces new struct `CANFilter` as well as `CANSocket` function `set_filter`, which wraps the appropriate `setsockopt` call.

Add initial frame filtering

---

src/lib.rs

Hi Marc,
LIBC's timeval struct is defined as this:
```
timeval {
tv_sec: time_t;
tv_usec: suseconds_t
}
```
Those types are available in rust as well, and for that reason should be used.
I had to fix that to use socketcan on x86_64 macos, where `tv_sec` is an i64 while `tv_usec` is an i32. Some differencies may appear on other platforms as well.
Although macos does not support CAN interface, as we use macbooks for development it is very handy to use socketcan for replaying can dumps
Note that this patch works well on top of release 1.6.0; on master branch I get even more errors because of the new dependency to `netlink-rs`. If you accept this change, it would be nice to publish a fixed release 1.6.1!
Best regards

Use libc types instead of manually choosing i32 or i64

---

.github/workflows/ci.yml

Basically a copy from [actions-rs/meta](https://github.com/actions-rs/meta) with adapted MSRV. I think it might make sense to add the [security-audit](https://github.com/actions-rs/meta/blob/master/recipes/security-audit.md) job as well in the future but I think that requires separate secret variable config in the repository.

Setup GH action based on actions-rs/meta template

---

Cargo.toml
src/nl.rs

Hi everyone, 
this is a first step towards the requirements in #32. Specifically, it implements: 
- creating vcan (and theoretically other) CAN interfaces
- deleting interfaces
- reading rudimentary interface data (name, MTU, up/down) (can be extended easily by adding more entries in the corresponding loop)
- setting MTU (switching VCAN from FD to non-FD and vice versa) 
All of the tests added here need to be run as root and/or with CAP_NET_ADMIN capability. As such, I hid them behind another feature flag. They work locally for me. 
I did not get to bitrate and such because that actually does not work with vcan out-of-the-box; and I don't have a physical CAN device at home atm. 
For follow-up changes it might be interesting to know where I got the information from (which was quite painful …

Netlink extensions (issue #32)

---

Cargo.toml
src/lib.rs
src/socket.rs
src/socket/async_io.rs
tests/cansocket-asyncio.rs

As discussed in #39, this adds basic support for async-io based async runtimes like async-std and smol. Couple of notes: 
- ~~I did not add a direct constructor, instead relying on TryFrom<CanSocket/CanFdSocket>. This could be added easily though.~~
- I did not add a method to get back to the synchronous socket, partially because I haven't figured out how to do that yet. 
- I pretty much only ported the read and write functionality, since setting socket options is not possible asynchronously on Linux. To maintain access to the different setup methods, I give access to the inner socket via `as_sync_socket` methods. 
- ~~Instead of using the mem::zeroed-based approach when reading, I actually went with the MaybeUninit strategy, which I believe to be sound. However, I can go back to the …

add basic support for async-io

---

src/nl.rs

add set_bitrate method using netlink API

add set_bitrate method

---

src/tokio.rs

... Wish I had checked the pull requests and seen number #51 already, I wouldn't have implemented this 😬
This takes a slightly different approach in that I made the interfaces generic, not sure if you like it more or less,
so figure I should post it just in case.
I also did a stream impl and copy pasta'ed the tests and made minor tweaks.
the stream tests pass when run independently but are non-deterministic as part of cargo test, not sure if that's existing behavior.
Thanks for the library, feel free to close this or lift anything you want out of it.

Async CanFD via Generics

---

src/nl/mod.rs

This fixes `termination` in the user facing api to be an `u16` like it is in the kernel and then adds a set_termination function to set the internal termination resistor, for can interfaces that support it.

Make termination u16 and add set_termination

---

src/nl/mod.rs
src/nl/rt.rs

This change enables pattern matching of `enum CanState` from client code by marking it as `pub`.
I've also restructured comments so that compiler doesn't complain about missing docs.
Let me know if you think this change requires more thought.

Make CanState public

---

src/errors.rs
src/frame.rs
src/lib.rs
src/nl/rt.rs

While compiling with rustc version 1.78 i got these errors related to unnecessary qualifications, hence i removed these qualifications.

remove unnecessary qualifications

---

src/socket.rs

Reading a standard CAN frame through the `CanFdSocket` leads to a crash due to mismatching sizes in the frame construction’s `copy_from_slice`. Thix fix has been tested and builds valid CAN frames.

`CanFdSocket` read_frame crash fix

---

src/dump.rs

Would you be open to merging this?
I haven't looked into _why_ my candump has a \r\n rather than just a \n at the line ending but it does.

Dump parsing also optionally trims off CR at the line end

---

Cargo.toml
examples/tokio_average.rs
examples/tokio_bridge.rs
examples/tokio_send.rs
src/socket.rs
src/tokio.rs

Hello,
I was studying the tokio async implementation for the `CanSocket`/`CanFdSocket` and noticed that the implementation seems out of date compared to what the current tokio API offers (using the `AsyncFd`). Instead of having the intermediate `EventedCanSocket` wrapper, which implements a mio event source, I directly used the appropriate functions on the `AsyncFd`. I could not figure out why the mio event source was used as an intermediate wrapper. My only guess is that the code was merged from the tokio-socketcan crate, which wasn't updated for a long time, and was written against an older API of tokio/mio. If I am wrong here and the code was necessary for some reason, please let me know!
When working on it, I also added a new method for reading a single frame asynchronously, which was …

Improved tokio async implementation

---

src/lib.rs
src/nl/mod.rs

This new method allows to set multiple CAN-specific parameters at once instead of over multiple netlink messages.
This is also required for some more obscure devices which might not accept some parameter configurations split over multiple netlink messages.

CanInterface: add set_can_params method to set multiple parameters

---

Cargo.toml
src/nl/mod.rs
src/socket.rs

This crate is causing a lot of duplicate dependencies in our trees since it uses outdated versions of some very common libraries.
This PR updates these dependencies to their latest version. Only the `nix` dependency required some code changes.

Update some dependencies

---

Cargo.toml
build.rs

I tried to make it a bit friendlier for someone accidentally building on non-linux by adding a build script to check and only including neli for linux. Also this removes an unused and very outdated dependency as well as updating thiserror to version 2, which has permeated through the ecosystem quite a bit

Friendly non linux compilation error

---

src/nl/mod.rs

This intended for testing if a CanCtrlModes has a certain CanCtrlMode set. If you obtain an InterfaceCanParams from the CanInterface, you can inspect what CanCtrlMode bits are set or not.

Add CanCtrlModes::has_mode(mode: CanCtrlMode)

---

src/frame.rs

This PR fixes the calculation of the data length code (DLC) for CANFD frames with extended data length.
The current code only returns the data length which is incorrect for frames with data length > 8 (also see: https://elearning.vector.com/mod/page/view.php?id=368)
I have currently implemented the fix so that `DLC=0` is returned if the data length is invalid. I am not completely satisfied with this solution, as a check when creating a CANFD frame would probably make more sense but requires changing the `CanFdFrame::init` function.
Please let me know what you think about this.

Fix DLC and add padding for CANFD frames

---

src/tokio.rs

The first patch is unrelated and is just a cleanup of a bunch of extraneous path components. I couldn't compile without removing these first.
I think this is probably an acceptable solution. This also fixes #57.
Please let me know what you think. I can probably test this on real hardware soon but the new tests pass (although they currently seem to omit actually verifying that the received frame is of the right type and content etc).

Support sending can frames over tokio canfd sockets (Resolves #57)
